[General]
allow-udp-proxy=false
bypass-tun=10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server=system,119.29.29.29,223.5.5.5
host=127.0.0.1
skip-proxy=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com

[Proxy]
ğŸ‡­ğŸ‡° Akari-HK = vmess,185.248.187.29,23981,chacha20-ietf-poly1305,"76160ceb-571b-42e6-93fe-d7d9ed8febc4",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡­ğŸ‡° Alibaba-HK = vmess,8.218.158.168,6665,chacha20-ietf-poly1305,"14ade852-509e-42f3-fcd7-837872db6ef1",over-tls=false,transport=ws,path=/,host=,skip-cert-verify=false
ğŸ‡²ğŸ‡¾ Alibaba-MY = vmess,47.254.241.169,15725,chacha20-ietf-poly1305,"97ae6e73-a487-41ce-b2dd-bce3b9b664d8",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡¸ğŸ‡¬ Alibaba-SG = vmess,47.236.20.150,19070,chacha20-ietf-poly1305,"0c13c13f-3beb-4028-bdad-24a48737f030",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡¯ğŸ‡µ Awesomecloud-JP = vmess,154.93.3.5,16302,chacha20-ietf-poly1305,"1c819c5e-d85c-4f68-b6b2-57f43c5b7180",over-tls=false,transport=ws,path=/,host=,skip-cert-verify=false
ğŸ‡¯ğŸ‡µ Awesomecloud-JP 2 = vmess,154.93.3.250,48710,chacha20-ietf-poly1305,"396384c1-16f4-485b-e7fc-a78dfff7c3cf",over-tls=false,transport=ws,path=/,host=,skip-cert-verify=false
ğŸ‡¦ğŸ‡º AWS-AU = vmess,13.236.232.142,443,chacha20-ietf-poly1305,"0cc17daa-f2ac-4449-e7c8-8d5b9d2bc007",over-tls=false,transport=ws,path=/,host=,skip-cert-verify=false
ğŸ‡°ğŸ‡· Azure-KR = vmess,20.196.226.111,54032,chacha20-ietf-poly1305,"a4ac41c5-0e5c-43e7-88e8-0966dec36734",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡¯ğŸ‡µ Linode-JP = Shadowsocks,172.104.87.35,65482,aes-256-gcm,"2XrfZTil8p"
ğŸ‡°ğŸ‡· Ntte-KR = Shadowsocks,112.196.223.64,55128,aes-256-gcm,"15823asdLa"
ğŸ‡¯ğŸ‡µ Oracle-JP = vmess,138.2.62.108,43330,chacha20-ietf-poly1305,"7691c693-ddb6-41fb-808d-30243c3ec3a9",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡¯ğŸ‡µ Oracle-JP 2 = vmess,64.110.103.245,33079,chacha20-ietf-poly1305,"17906350-6b0a-4623-b4cc-68e3e7469bf4",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡¯ğŸ‡µ Oracle-JP 3 = Shadowsocks,152.70.86.154,35176,aes-256-gcm,"gmBdrz5kBn"
ğŸ‡¯ğŸ‡µ Oracle-JP-ä¼˜é€‰ = vmess,162.159.129.217,80,chacha20-ietf-poly1305,"a6824d8a-3112-4123-9344-798112b1a1c3",over-tls=false,transport=ws,path=/dsabhdsa,host=150-230-97-54.lzmt.org,skip-cert-verify=false
ğŸ‡°ğŸ‡· Oracle-KR = vmess,152.70.89.135,59194,chacha20-ietf-poly1305,"58600d1a-e6e6-4d93-c291-13bed353563d",over-tls=false,transport=ws,path=/,host=,skip-cert-verify=false
ğŸ‡°ğŸ‡· Oracle-KR 2 = vmess,140.238.8.36,19220,chacha20-ietf-poly1305,"b4c91687-fae4-46db-bae5-c14e9bdaf04d",over-tls=false,transport=ws,path=/b4c91687,host=,skip-cert-verify=false
ğŸ‡°ğŸ‡· Oracle-KR 3 = vmess,130.162.159.77,29746,chacha20-ietf-poly1305,"ab74e8dc-41b0-491f-d9fc-dd41226f0b36",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡¸ğŸ‡¬ Oracle-SG-ä¼˜é€‰ = vmess,162.159.129.217,80,chacha20-ietf-poly1305,"93447aef-58ae-45d0-be2a-2aa636c38072",over-tls=false,transport=ws,path=/sa,host=129-150-59-244.lzmt.org,skip-cert-verify=false
ğŸ‡¸ğŸ‡¬ Tencent-SG = vmess,43.134.173.48,37787,chacha20-ietf-poly1305,"9c0e8629-e25e-4e04-fb8b-64e81d3a60cc",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡©ğŸ‡ª Linode-DE = vmess,143.42.18.37,51673,chacha20-ietf-poly1305,"8d954edc-8ee5-4407-b4af-3f5364e5c532",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡©ğŸ‡ª M247-DE = vmess,37.120.222.47,50506,chacha20-ietf-poly1305,"41af9313-f80c-40bc-fcc2-1930b52be2c8",over-tls=false,transport=tcp,skip-cert-verify=false
M247-NO = vmess,62.216.73.166,36129,chacha20-ietf-poly1305,"e91ed1f0-29dc-4b96-8527-c347d53fd2a7",over-tls=false,transport=ws,path=/,host=,skip-cert-verify=false
ğŸ‡¬ğŸ‡§ M247-UK = vmess,45.90.140.150,27713,chacha20-ietf-poly1305,"02863ef6-28f0-4ab3-da74-d2561b1fafc2",over-tls=false,transport=ws,path=/,host=,skip-cert-verify=false
Oracle-AE = vmess,193.123.82.177,49628,chacha20-ietf-poly1305,"4866c836-5adc-4b52-d408-c76142ceebdf",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡¬ğŸ‡§ Oracle-UK = vmess,130.162.180.96,37242,chacha20-ietf-poly1305,"4de3e1d2-fd6f-4253-b921-d0db9f32dabd",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡ºğŸ‡¸ Alibaba-US = vmess,47.88.10.46,50646,chacha20-ietf-poly1305,"2c8a64ff-e3de-440a-8462-ac117a0140a0",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡ºğŸ‡¸ Digitalvirt-US = vmess,154.40.62.118,23157,chacha20-ietf-poly1305,"e7583efe-47ba-4140-a8f8-a7ca3776218a",over-tls=false,transport=ws,path=/hgugh6,host=,skip-cert-verify=false
ğŸ‡ºğŸ‡¸ DMIT-US = vmess,174.136.207.179,44277,chacha20-ietf-poly1305,"cdff5c0a-2aa1-4174-8a52-05001dde8da8",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡ºğŸ‡¸ DMIT-US 2 = vmess,154.17.11.176,40517,chacha20-ietf-poly1305,"f84be62e-3cfb-48e0-b3f3-8402cc95c1d2",over-tls=false,transport=ws,path=/,host=,skip-cert-verify=false
ğŸ‡ºğŸ‡¸ Gcore-US = vmess,45.67.211.14,59047,chacha20-ietf-poly1305,"30812023-6a6f-4f1b-a1fe-89fc041ff3b0",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡ºğŸ‡¸ Olink-US = vmess,104.160.19.84,12362,chacha20-ietf-poly1305,"9b7bc233-ea07-4a6a-be3b-681578358bd6",over-tls=false,transport=tcp,skip-cert-verify=false
ğŸ‡¨ğŸ‡¦ Oracle-CA = vmess,155.248.227.34,35987,chacha20-ietf-poly1305,"20bf85b4-4703-47d1-fd8e-0fd3e158d8ff",over-tls=false,transport=tcp,skip-cert-verify=false

[Remote Proxy]

[Proxy Group]
ğŸš€ èŠ‚ç‚¹é€‰æ‹© = select,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸš€ æ‰‹åŠ¨åˆ‡æ¢ = select,ğŸ‡­ğŸ‡° Akari-HK,ğŸ‡­ğŸ‡° Alibaba-HK,ğŸ‡²ğŸ‡¾ Alibaba-MY,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¯ğŸ‡µ Awesomecloud-JP,ğŸ‡¯ğŸ‡µ Awesomecloud-JP 2,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡°ğŸ‡· Azure-KR,ğŸ‡¯ğŸ‡µ Linode-JP,ğŸ‡°ğŸ‡· Ntte-KR,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¯ğŸ‡µ Oracle-JP 3,ğŸ‡¯ğŸ‡µ Oracle-JP-ä¼˜é€‰,ğŸ‡°ğŸ‡· Oracle-KR,ğŸ‡°ğŸ‡· Oracle-KR 2,ğŸ‡°ğŸ‡· Oracle-KR 3,ğŸ‡¸ğŸ‡¬ Oracle-SG-ä¼˜é€‰,ğŸ‡¸ğŸ‡¬ Tencent-SG,ğŸ‡©ğŸ‡ª Linode-DE,ğŸ‡©ğŸ‡ª M247-DE,M247-NO,ğŸ‡¬ğŸ‡§ M247-UK,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ Alibaba-US,ğŸ‡ºğŸ‡¸ Digitalvirt-US,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ DMIT-US 2,ğŸ‡ºğŸ‡¸ Gcore-US,ğŸ‡ºğŸ‡¸ Olink-US,ğŸ‡¨ğŸ‡¦ Oracle-CA
ğŸ“² ç”µæŠ¥æ¶ˆæ¯ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ’¬ OpenAi = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ“¹ æ²¹ç®¡è§†é¢‘ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ¥ å¥ˆé£è§†é¢‘ = select,ğŸ¥ å¥ˆé£èŠ‚ç‚¹,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ“º å·´å“ˆå§†ç‰¹ = select,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ“º å“”å“©å“”å“© = select,ğŸ¯ å…¨çƒç›´è¿,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
ğŸŒ å›½å¤–åª’ä½“ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸŒ å›½å†…åª’ä½“ = select,DIRECT,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ“¢ è°·æ­ŒFCM = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
â“‚ï¸ å¾®è½¯äº‘ç›˜ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
â“‚ï¸ å¾®è½¯æœåŠ¡ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ è‹¹æœæœåŠ¡ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ® æ¸¸æˆå¹³å° = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ¶ ç½‘æ˜“éŸ³ä¹ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
ğŸ¯ å…¨çƒç›´è¿ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
ğŸ›‘ å¹¿å‘Šæ‹¦æˆª = select,REJECT,DIRECT
ğŸƒ åº”ç”¨å‡€åŒ– = select,REJECT,DIRECT
ğŸŸ æ¼ç½‘ä¹‹é±¼ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,DIRECT,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹ = select,ğŸ‡­ğŸ‡° Akari-HK,ğŸ‡­ğŸ‡° Alibaba-HK
ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹ = select,ğŸ‡¯ğŸ‡µ Awesomecloud-JP,ğŸ‡¯ğŸ‡µ Awesomecloud-JP 2,ğŸ‡¯ğŸ‡µ Linode-JP,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¯ğŸ‡µ Oracle-JP 3,ğŸ‡¯ğŸ‡µ Oracle-JP-ä¼˜é€‰
ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹ = select,ğŸ‡ºğŸ‡¸ Alibaba-US,ğŸ‡ºğŸ‡¸ Digitalvirt-US,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ DMIT-US 2,ğŸ‡ºğŸ‡¸ Gcore-US,ğŸ‡ºğŸ‡¸ Olink-US
ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹ = select,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¸ğŸ‡¬ Oracle-SG-ä¼˜é€‰,ğŸ‡¸ğŸ‡¬ Tencent-SG
ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹ = select,DIRECT
ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹ = select,ğŸ‡°ğŸ‡· Azure-KR,ğŸ‡°ğŸ‡· Ntte-KR,ğŸ‡°ğŸ‡· Oracle-KR,ğŸ‡°ğŸ‡· Oracle-KR 2,ğŸ‡°ğŸ‡· Oracle-KR 3
ğŸ¥ å¥ˆé£èŠ‚ç‚¹ = select,DIRECT

[Rule]
GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
FINAL,ğŸŸ æ¼ç½‘ä¹‹é±¼

[Remote Rule]
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,ğŸ¯ å…¨çƒç›´è¿
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,ğŸ¯ å…¨çƒç›´è¿
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,ğŸƒ åº”ç”¨å‡€åŒ–
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,ğŸ“¢ è°·æ­ŒFCM
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,ğŸ¯ å…¨çƒç›´è¿
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,ğŸ¯ å…¨çƒç›´è¿
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list,â“‚ï¸ å¾®è½¯äº‘ç›˜
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,â“‚ï¸ å¾®è½¯æœåŠ¡
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,ğŸ è‹¹æœæœåŠ¡
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list,ğŸ’¬ OpenAi
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list,ğŸ¶ ç½‘æ˜“éŸ³ä¹
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list,ğŸ® æ¸¸æˆå¹³å°
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list,ğŸ® æ¸¸æˆå¹³å°
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list,ğŸ® æ¸¸æˆå¹³å°
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list,ğŸ® æ¸¸æˆå¹³å°
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list,ğŸ® æ¸¸æˆå¹³å°
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list,ğŸ“¹ æ²¹ç®¡è§†é¢‘
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list,ğŸ¥ å¥ˆé£è§†é¢‘
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list,ğŸ“º å·´å“ˆå§†ç‰¹
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list,ğŸ“º å“”å“©å“”å“©
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list,ğŸ“º å“”å“©å“”å“©
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list,ğŸŒ å›½å†…åª’ä½“
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,ğŸŒ å›½å¤–åª’ä½“
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,ğŸ¯ å…¨çƒç›´è¿
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,ğŸ¯ å…¨çƒç›´è¿
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list,ğŸ¯ å…¨çƒç›´è¿

[URL Rewrite]
enable=true
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302

[Remote Rewrite]
https://raw.githubusercontent.com/Loon0x00/LoonExampleConfig/master/Rewrite/AutoRewrite_Example.list,auto

[MITM]
enable=true
hostname=*.example.com,*.sample.com
skip-server-cert-verify=true

