#!MANAGED-CONFIG https://www.shadowsocksr.link/config/xui/surge.yaml

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNSè®¾ç½®æˆ–æ ¹æ®è‡ªå·±ç½‘ç»œæƒ…å†µè¿›è¡Œç›¸åº”è®¾ç½®
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5

[Script]
http-request https?:\/\/.*\.iqiyi\.com\/.*authcookie= script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[Proxy]
DIRECT = direct
ğŸ‡¨ğŸ‡³ Akile-TW = trojan, 141-11-86-247.lzmt.org, 25380, password=MTDdEJCl6F, sni=141-11-86-247.lzmt.org
ğŸ‡¸ğŸ‡¬ Alibaba-SG = vmess, 47.236.20.150, 19070, username=0c13c13f-3beb-4028-bdad-24a48737f030, tls=false, vmess-aead=true
ğŸ‡¦ğŸ‡º AWS-AU = vmess, 13.236.232.142, 443, username=0cc17daa-f2ac-4449-e7c8-8d5b9d2bc007, tls=false, vmess-aead=true, ws=true, ws-path=/, sni=13.236.232.142
ğŸ‡¨ğŸ‡³ Hinet-TW = vmess, hinet.lzmt.org, 64002, username=8519482b-3ac3-46ed-e905-9116cefc5d31, tls=false, vmess-aead=true
ğŸ‡¯ğŸ‡µ Oracle-JP = vmess, 138.2.62.108, 43330, username=7691c693-ddb6-41fb-808d-30243c3ec3a9, tls=false, vmess-aead=true
ğŸ‡¯ğŸ‡µ Oracle-JP 2 = vmess, 64.110.103.245, 33079, username=17906350-6b0a-4623-b4cc-68e3e7469bf4, tls=false, vmess-aead=true
ğŸ‡¸ğŸ‡¬ Speedypage-SG = trojan, 103-166-228-66.lzmt.org, 12076, password=79YeGvQ1Ok, sni=103-166-228-66.lzmt.org
Oracle-AE = vmess, 193.123.82.177, 49628, username=4866c836-5adc-4b52-d408-c76142ceebdf, tls=false, vmess-aead=true
ğŸ‡¬ğŸ‡§ Oracle-UK = vmess, 130.162.180.96, 37242, username=4de3e1d2-fd6f-4253-b921-d0db9f32dabd, tls=false, vmess-aead=true
ğŸ‡ºğŸ‡¸ DMIT-US = vmess, 174.136.207.179, 44277, username=cdff5c0a-2aa1-4174-8a52-05001dde8da8, tls=false, vmess-aead=true
ğŸ‡ºğŸ‡¸ Misaka-US = trojan, 38-175-102-34.lzmt.org, 31358, password=XgSpn1eHTv, sni=38-175-102-34.lzmt.org
ğŸ‡ºğŸ‡¸ Olink-US = vmess, 104.160.19.84, 12362, username=9b7bc233-ea07-4a6a-be3b-681578358bd6, tls=false, vmess-aead=true

[Proxy Group]
ğŸš€ èŠ‚ç‚¹é€‰æ‹© = select,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,DIRECT,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡¨ğŸ‡³ Hinet-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¸ğŸ‡¬ Speedypage-SG,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡ºğŸ‡¸ Olink-US
â™»ï¸ è‡ªåŠ¨é€‰æ‹© = url-test,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡¨ğŸ‡³ Hinet-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¸ğŸ‡¬ Speedypage-SG,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡ºğŸ‡¸ Olink-US,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
ğŸŒ å›½å¤–åª’ä½“ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡¨ğŸ‡³ Hinet-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¸ğŸ‡¬ Speedypage-SG,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡ºğŸ‡¸ Olink-US
ğŸ“² ç”µæŠ¥ä¿¡æ¯ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡¨ğŸ‡³ Hinet-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¸ğŸ‡¬ Speedypage-SG,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡ºğŸ‡¸ Olink-US
â“‚ï¸ å¾®è½¯æœåŠ¡ = select,ğŸ¯ å…¨çƒç›´è¿,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡¨ğŸ‡³ Hinet-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¸ğŸ‡¬ Speedypage-SG,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡ºğŸ‡¸ Olink-US
ğŸ è‹¹æœæœåŠ¡ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡¨ğŸ‡³ Hinet-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¸ğŸ‡¬ Speedypage-SG,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡ºğŸ‡¸ Olink-US
ğŸ“¢ è°·æ­ŒFCM = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡¨ğŸ‡³ Hinet-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¸ğŸ‡¬ Speedypage-SG,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡ºğŸ‡¸ Olink-US
ğŸ¯ å…¨çƒç›´è¿ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
ğŸ›‘ å…¨çƒæ‹¦æˆª = select,REJECT,DIRECT
ğŸƒ åº”ç”¨å‡€åŒ– = select,REJECT,DIRECT
ğŸŸ æ¼ç½‘ä¹‹é±¼ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡¸ğŸ‡¬ Alibaba-SG,ğŸ‡¦ğŸ‡º AWS-AU,ğŸ‡¨ğŸ‡³ Hinet-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¯ğŸ‡µ Oracle-JP 2,ğŸ‡¸ğŸ‡¬ Speedypage-SG,Oracle-AE,ğŸ‡¬ğŸ‡§ Oracle-UK,ğŸ‡ºğŸ‡¸ DMIT-US,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡ºğŸ‡¸ Olink-US

[Rule]
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,ğŸ›‘ å…¨çƒæ‹¦æˆª,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,ğŸƒ åº”ç”¨å‡€åŒ–,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,ğŸ“¢ è°·æ­ŒFCM,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,â“‚ï¸ å¾®è½¯æœåŠ¡,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,ğŸ è‹¹æœæœåŠ¡,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,ğŸ“² ç”µæŠ¥ä¿¡æ¯,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,ğŸŒ å›½å¤–åª’ä½“,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
FINAL,ğŸŸ æ¼ç½‘ä¹‹é±¼

