#!MANAGED-CONFIG https://www.shadowsocksr.link/config/xui/surge.yaml

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNSè®¾ç½®æˆ–æ ¹æ®è‡ªå·±ç½‘ç»œæƒ…å†µè¿›è¡Œç›¸åº”è®¾ç½®
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5

[Script]
http-request https?:\/\/.*\.iqiyi\.com\/.*authcookie= script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[Proxy]
DIRECT = direct
ğŸ‡¨ğŸ‡³ Akile-TW = ss, tw-1.ac.laowanxiang.com, 14732, encrypt-method=aes-256-gcm, password=loruXwHJVt
ğŸ‡­ğŸ‡° AperNet-HK = trojan, hk-pop-1.ac.laowanxiang.com, 14732, password=mLgIX7VmRH, sni=23-247-139-58.lzmt.org
ğŸ‡¯ğŸ‡µ Catixs-JP = ss, jp-2.ac.laowanxiang.com, 14732, encrypt-method=none, password=doub.io
ğŸ‡¨ğŸ‡¦ Gocodeit-CA = ss, hk06.wsfsa.top, 32202, encrypt-method=aes-256-gcm, password=mMoE4F0N0B
ğŸ‡¨ğŸ‡³ Hinet-TW = ss, hk06.wsfsa.top, 32205, encrypt-method=aes-256-gcm, password=HXNWNrJwvm
JJSpa-CL = ss, sg-1.ac.laowanxiang.com, 14732, encrypt-method=aes-256-gcm, password=8MBbKcik1Q
Markahost-TR = ss, dmit_hk1.qiangdong.xyz, 14732, encrypt-method=aes-256-gcm, password=pIgdtbQ18s
ğŸ‡ºğŸ‡¸ Misaka-US = ss, hk06.wsfsa.top, 32203, encrypt-method=aes-256-gcm, password=n1c3uCruks
ğŸ‡°ğŸ‡· Moack-KR = ss, hk06.wsfsa.top, 32207, encrypt-method=aes-256-gcm, password=BLxDqjZEdd
ğŸ‡¨ğŸ‡³ NeroCloud-TW = ss, 183.240.220.206, 14732, encrypt-method=aes-256-gcm, password=AGyfAT72g1
ğŸ‡¯ğŸ‡µ Oracle-JP = vmess, jp-1.ac.laowanxiang.com, 14732, username=17906350-6b0a-4623-b4cc-68e3e7469bf4, tls=false, vmess-aead=true
ğŸ‡¸ğŸ‡¬ Speedypage-SG = ss, hk06.wsfsa.top, 32204, encrypt-method=aes-256-gcm, password=LHngT5qTKx
ğŸ‡©ğŸ‡° Stacket-DK = ss, hk06.wsfsa.top, 32206, encrypt-method=aes-256-gcm, password=yBlREYCIeX

[Proxy Group]
ğŸš€ èŠ‚ç‚¹é€‰æ‹© = select,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,DIRECT,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡­ğŸ‡° AperNet-HK,ğŸ‡¯ğŸ‡µ Catixs-JP,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,ğŸ‡¨ğŸ‡³ Hinet-TW,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡°ğŸ‡· Moack-KR,ğŸ‡¨ğŸ‡³ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¸ğŸ‡¬ Speedypage-SG,ğŸ‡©ğŸ‡° Stacket-DK
â™»ï¸ è‡ªåŠ¨é€‰æ‹© = url-test,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡­ğŸ‡° AperNet-HK,ğŸ‡¯ğŸ‡µ Catixs-JP,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,ğŸ‡¨ğŸ‡³ Hinet-TW,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡°ğŸ‡· Moack-KR,ğŸ‡¨ğŸ‡³ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¸ğŸ‡¬ Speedypage-SG,ğŸ‡©ğŸ‡° Stacket-DK,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
ğŸŒ å›½å¤–åª’ä½“ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡­ğŸ‡° AperNet-HK,ğŸ‡¯ğŸ‡µ Catixs-JP,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,ğŸ‡¨ğŸ‡³ Hinet-TW,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡°ğŸ‡· Moack-KR,ğŸ‡¨ğŸ‡³ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¸ğŸ‡¬ Speedypage-SG,ğŸ‡©ğŸ‡° Stacket-DK
ğŸ“² ç”µæŠ¥ä¿¡æ¯ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡­ğŸ‡° AperNet-HK,ğŸ‡¯ğŸ‡µ Catixs-JP,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,ğŸ‡¨ğŸ‡³ Hinet-TW,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡°ğŸ‡· Moack-KR,ğŸ‡¨ğŸ‡³ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¸ğŸ‡¬ Speedypage-SG,ğŸ‡©ğŸ‡° Stacket-DK
â“‚ï¸ å¾®è½¯æœåŠ¡ = select,ğŸ¯ å…¨çƒç›´è¿,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡­ğŸ‡° AperNet-HK,ğŸ‡¯ğŸ‡µ Catixs-JP,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,ğŸ‡¨ğŸ‡³ Hinet-TW,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡°ğŸ‡· Moack-KR,ğŸ‡¨ğŸ‡³ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¸ğŸ‡¬ Speedypage-SG,ğŸ‡©ğŸ‡° Stacket-DK
ğŸ è‹¹æœæœåŠ¡ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡­ğŸ‡° AperNet-HK,ğŸ‡¯ğŸ‡µ Catixs-JP,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,ğŸ‡¨ğŸ‡³ Hinet-TW,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡°ğŸ‡· Moack-KR,ğŸ‡¨ğŸ‡³ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¸ğŸ‡¬ Speedypage-SG,ğŸ‡©ğŸ‡° Stacket-DK
ğŸ“¢ è°·æ­ŒFCM = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡­ğŸ‡° AperNet-HK,ğŸ‡¯ğŸ‡µ Catixs-JP,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,ğŸ‡¨ğŸ‡³ Hinet-TW,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡°ğŸ‡· Moack-KR,ğŸ‡¨ğŸ‡³ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¸ğŸ‡¬ Speedypage-SG,ğŸ‡©ğŸ‡° Stacket-DK
ğŸ¯ å…¨çƒç›´è¿ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
ğŸ›‘ å…¨çƒæ‹¦æˆª = select,REJECT,DIRECT
ğŸƒ åº”ç”¨å‡€åŒ– = select,REJECT,DIRECT
ğŸŸ æ¼ç½‘ä¹‹é±¼ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ¯ å…¨çƒç›´è¿,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,ğŸ‡¨ğŸ‡³ Akile-TW,ğŸ‡­ğŸ‡° AperNet-HK,ğŸ‡¯ğŸ‡µ Catixs-JP,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,ğŸ‡¨ğŸ‡³ Hinet-TW,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡°ğŸ‡· Moack-KR,ğŸ‡¨ğŸ‡³ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP,ğŸ‡¸ğŸ‡¬ Speedypage-SG,ğŸ‡©ğŸ‡° Stacket-DK

[Rule]
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,ğŸ›‘ å…¨çƒæ‹¦æˆª,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,ğŸƒ åº”ç”¨å‡€åŒ–,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,ğŸ“¢ è°·æ­ŒFCM,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,â“‚ï¸ å¾®è½¯æœåŠ¡,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,ğŸ è‹¹æœæœåŠ¡,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,ğŸ“² ç”µæŠ¥ä¿¡æ¯,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,ğŸŒ å›½å¤–åª’ä½“,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
FINAL,ğŸŸ æ¼ç½‘ä¹‹é±¼

