#!MANAGED-CONFIG https://api.v1.mk/sub?target=surge&ver=4&url=ss%3A%2F%2FYWVzLTI1Ni1nY206bG9ydVh3SEpWdA%3D%3D%40111.38.37.15%3A26782%23Akile-TW%7Css%3A%2F%2FYWVzLTI1Ni1nY206ZFluYmVLTXBQZA%3D%3D%40183.233.187.244%3A27357%23DMIT-HK%7Css%3A%2F%2Fbm9uZTpkb3ViLmlv%40178.173.255.20%3A27093%23Eons-HK%7Css%3A%2F%2FYWVzLTI1Ni1nY206c25pdVJuOUhpZw%3D%3D%4036.139.239.208%3A46263%23Eons-JP%7Css%3A%2F%2FYWVzLTI1Ni1nY206UHI0SjZDTGtKZA%3D%3D%40111.38.37.15%3A25980%23Eons-SG%7Css%3A%2F%2FYWVzLTI1Ni1nY206bU1vRTRGME4wQg%3D%3D%40183.233.187.244%3A27951%23Gocodeit-CA%7Css%3A%2F%2FYWVzLTI1Ni1nY206OE1CYktjaWsxUQ%3D%3D%40200.14.81.180%3A53731%23JJSpa-CL%7Css%3A%2F%2FYWVzLTI1Ni1nY206cElnZHRiUTE4cw%3D%3D%40213.238.182.236%3A54780%23Markahost-TR%7Css%3A%2F%2FYWVzLTI1Ni1nY206bjFjM3VDcnVrcw%3D%3D%4058.242.130.170%3A26244%23Misaka-US%7Css%3A%2F%2FYWVzLTI1Ni1nY206QUd5ZkFUNzJnMQ%3D%3D%40209.146.125.194%3A45631%23NeroCloud-TW%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogIk9yYWNsZS1KUCIsDQogICJhZGQiOiAiNjQuMTEwLjEwMy4yNDUiLA0KICAicG9ydCI6ICIzMzA3OSIsDQogICJpZCI6ICIxNzkwNjM1MC02YjBhLTQ2MjMtYjRjYy02OGUzZTc0NjliZjQiLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogInRjcCIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIiLA0KICAidGxzIjogIm5vbmUiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0%3D%7C&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false interval=86400 strict=false

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNSè®¾ç½®æˆ–æ ¹æ®è‡ªå·±ç½‘ç»œæƒ…å†µè¿›è¡Œç›¸åº”è®¾ç½®
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5,218.30.19.40,61.134.1.4
external-controller-access = password@0.0.0.0:6170
http-api = password@0.0.0.0:6171
test-timeout = 5
http-api-web-dashboard = true
exclude-simple-hostnames = true
allow-wifi-access = true
http-listen = 0.0.0.0:6152
socks5-listen = 0.0.0.0:6153
wifi-access-http-port = 6152
wifi-access-socks5-port = 6153

[Script]
http-request https?:\/\/.*\.iqiyi\.com\/.*authcookie= script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[Proxy]
DIRECT = direct
ğŸ‡¹ğŸ‡¼ Akile-TW = ss, 111.38.37.15, 26782, encrypt-method=aes-256-gcm, password=loruXwHJVt, tfo=false, udp-relay=false
ğŸ‡­ğŸ‡° DMIT-HK = ss, 183.233.187.244, 27357, encrypt-method=aes-256-gcm, password=dYnbeKMpPd, tfo=false, udp-relay=false
ğŸ‡­ğŸ‡° Eons-HK = ss, 178.173.255.20, 27093, encrypt-method=none, password=doub.io, tfo=false, udp-relay=false
ğŸ‡¯ğŸ‡µ Eons-JP = ss, 36.139.239.208, 46263, encrypt-method=aes-256-gcm, password=sniuRn9Hig, tfo=false, udp-relay=false
ğŸ‡¸ğŸ‡¬ Eons-SG = ss, 111.38.37.15, 25980, encrypt-method=aes-256-gcm, password=Pr4J6CLkJd, tfo=false, udp-relay=false
ğŸ‡¨ğŸ‡¦ Gocodeit-CA = ss, 183.233.187.244, 27951, encrypt-method=aes-256-gcm, password=mMoE4F0N0B, tfo=false, udp-relay=false
JJSpa-CL = ss, 200.14.81.180, 53731, encrypt-method=aes-256-gcm, password=8MBbKcik1Q, tfo=false, udp-relay=false
Markahost-TR = ss, 213.238.182.236, 54780, encrypt-method=aes-256-gcm, password=pIgdtbQ18s, tfo=false, udp-relay=false
ğŸ‡ºğŸ‡¸ Misaka-US = ss, 58.242.130.170, 26244, encrypt-method=aes-256-gcm, password=n1c3uCruks, tfo=false, udp-relay=false
ğŸ‡¹ğŸ‡¼ NeroCloud-TW = ss, 209.146.125.194, 45631, encrypt-method=aes-256-gcm, password=AGyfAT72g1, tfo=false, udp-relay=false
ğŸ‡¯ğŸ‡µ Oracle-JP = vmess, 64.110.103.245, 33079, username=17906350-6b0a-4623-b4cc-68e3e7469bf4, tls=false, vmess-aead=true, skip-cert-verify=false, tfo=false, udp-relay=false
ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹ = direct
ğŸ¥ å¥ˆé£èŠ‚ç‚¹ = direct

[Proxy Group]
ğŸš€ èŠ‚ç‚¹é€‰æ‹© = select,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸš€ æ‰‹åŠ¨åˆ‡æ¢ = select,ğŸ‡¹ğŸ‡¼ Akile-TW,ğŸ‡­ğŸ‡° DMIT-HK,ğŸ‡­ğŸ‡° Eons-HK,ğŸ‡¯ğŸ‡µ Eons-JP,ğŸ‡¸ğŸ‡¬ Eons-SG,ğŸ‡¨ğŸ‡¦ Gocodeit-CA,JJSpa-CL,Markahost-TR,ğŸ‡ºğŸ‡¸ Misaka-US,ğŸ‡¹ğŸ‡¼ NeroCloud-TW,ğŸ‡¯ğŸ‡µ Oracle-JP
ğŸ“² ç”µæŠ¥æ¶ˆæ¯ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ’¬ OpenAi = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ“¹ æ²¹ç®¡è§†é¢‘ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ¥ å¥ˆé£è§†é¢‘ = select,ğŸ¥ å¥ˆé£èŠ‚ç‚¹,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ“º å·´å“ˆå§†ç‰¹ = select,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸ“º å“”å“©å“”å“© = select,ğŸ¯ å…¨çƒç›´è¿,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
ğŸŒ å›½å¤–åª’ä½“ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢,DIRECT
ğŸŒ å›½å†…åª’ä½“ = select,DIRECT,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ“¢ è°·æ­ŒFCM = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
â“‚ï¸ å¾®è½¯Bing = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
â“‚ï¸ å¾®è½¯äº‘ç›˜ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
â“‚ï¸ å¾®è½¯æœåŠ¡ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ è‹¹æœæœåŠ¡ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ® æ¸¸æˆå¹³å° = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ¶ ç½‘æ˜“éŸ³ä¹ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
ğŸ¯ å…¨çƒç›´è¿ = select,DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
ğŸ›‘ å¹¿å‘Šæ‹¦æˆª = select,REJECT,DIRECT
ğŸƒ åº”ç”¨å‡€åŒ– = select,REJECT,DIRECT
ğŸŸ æ¼ç½‘ä¹‹é±¼ = select,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,DIRECT,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹,ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹ = select,ğŸ‡­ğŸ‡° DMIT-HK,ğŸ‡­ğŸ‡° Eons-HK
ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹ = select,ğŸ‡¯ğŸ‡µ Eons-JP,ğŸ‡¯ğŸ‡µ Oracle-JP
ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹ = select,ğŸ‡ºğŸ‡¸ Misaka-US
ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹ = select,ğŸ‡¸ğŸ‡¬ Eons-SG
ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹ = select,ğŸ‡¹ğŸ‡¼ Akile-TW,ğŸ‡¹ğŸ‡¼ NeroCloud-TW

[Rule]
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,ğŸƒ åº”ç”¨å‡€åŒ–,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,ğŸ“¢ è°·æ­ŒFCM,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list,â“‚ï¸ å¾®è½¯Bing,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list,â“‚ï¸ å¾®è½¯äº‘ç›˜,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,â“‚ï¸ å¾®è½¯æœåŠ¡,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,ğŸ è‹¹æœæœåŠ¡,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,ğŸ“² ç”µæŠ¥æ¶ˆæ¯,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list,ğŸ’¬ OpenAi,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list,ğŸ¶ ç½‘æ˜“éŸ³ä¹,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list,ğŸ® æ¸¸æˆå¹³å°,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list,ğŸ® æ¸¸æˆå¹³å°,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list,ğŸ® æ¸¸æˆå¹³å°,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list,ğŸ® æ¸¸æˆå¹³å°,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list,ğŸ® æ¸¸æˆå¹³å°,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list,ğŸ“¹ æ²¹ç®¡è§†é¢‘,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list,ğŸ¥ å¥ˆé£è§†é¢‘,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list,ğŸ“º å·´å“ˆå§†ç‰¹,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list,ğŸ“º å“”å“©å“”å“©,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list,ğŸ“º å“”å“©å“”å“©,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list,ğŸŒ å›½å†…åª’ä½“,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,ğŸŒ å›½å¤–åª’ä½“,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list,ğŸ¯ å…¨çƒç›´è¿,update-interval=86400
GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
FINAL,ğŸŸ æ¼ç½‘ä¹‹é±¼